### ISSUE TITLE
CoinAPI key requires quotes

### ISSUE THREAD

**Issue by sophware** [williamkray/maubot-ticker#3]
...or at least it did, in my case. This is a lazy issue report. Let me know if I should include more details, including logs.

**Comment by williamkray** [comment]
interesting... i definitely did not need quotes around my coinAPI key. my maubot is running in docker with the official docker image.

does your api key have special characters in it or anything? mine is alphanumeric with hyphens, but perhaps they've changed their format.

**Comment by sophware** [comment]
Strange. Yeah, my key is the same style as yours. Must be something strange about my environment.
